import React from 'react';
import {
  GridZoneData,
  GridConnection,
  TransferPlanItem,
  GridPartition,
  SimulationResult,
} from '../types';
import { GridTopologyGraph } from '../components/GridTopologyGraph';
import {
  ArrowRightLeft,
  Download,
  Printer,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Zap,
} from 'lucide-react';

interface TransferPlanPageProps {
  zones: GridZoneData[];
  connections: GridConnection[];
  recommendations: TransferPlanItem[];
  partitions: GridPartition[];
  simulationResult: SimulationResult;
  onRunSimulation: () => void;
  isRunningSimulation: boolean;
  onSelectZone: (zone: GridZoneData) => void;
  onDownloadReport: () => void;
}

export const TransferPlanPage: React.FC<TransferPlanPageProps> = ({
  zones,
  connections,
  recommendations,
  partitions,
  simulationResult,
  onRunSimulation,
  isRunningSimulation,
  onSelectZone,
  onDownloadReport,
}) => {
  const overloadedBefore = zones.filter((z) => z.forecastLoadMw > z.capacityMw);
  const totalShifted = recommendations.reduce((sum, r) => sum + r.transferMw, 0);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Top Banner & Export Actions */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-5 shadow-2xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-xs font-bold text-blue-700 uppercase tracking-wider">
            <ArrowRightLeft className="w-4 h-4" />
            <span>Load Balancing Dispatch Plan</span>
          </div>
          <h2 className="text-xl font-bold tracking-tight text-slate-900">
            Recommended Energy Transfer Plan
          </h2>
          <p className="text-xs text-slate-600 max-w-2xl">
            Simulated transfer schedule generated by Java LoadBalancer adhering to direct graph adjacency, line thermal limits, and safe recipient thresholds.
          </p>
        </div>

        <div className="flex items-center gap-2.5 shrink-0 flex-wrap">
          <button
            onClick={handlePrint}
            className="px-3.5 py-2 bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-700 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>

          <button
            onClick={onDownloadReport}
            className="px-3.5 py-2 bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-700 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={onRunSimulation}
            disabled={isRunningSimulation}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-semibold shadow-xs transition-colors flex items-center gap-2 cursor-pointer disabled:opacity-50"
          >
            <Zap className="w-3.5 h-3.5 fill-white" />
            <span>Re-run Simulation</span>
          </button>
        </div>
      </div>

      {/* Overload Status Overview Callout */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="p-4 bg-white border border-slate-200/90 rounded-xl shadow-2xs">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Pre-Transfer Overload</span>
          <div className="mt-1 flex items-baseline gap-2">
            <span className={`text-2xl font-bold font-mono ${overloadedBefore.length > 0 ? 'text-rose-600' : 'text-slate-900'}`}>
              {overloadedBefore.length}
            </span>
            <span className="text-xs text-slate-500">Zone(s) at risk</span>
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            {overloadedBefore.length > 0
              ? `Surge detected in ${overloadedBefore.map((z) => z.name).join(', ')}`
              : 'All zones safe before transfer'}
          </div>
        </div>

        <div className="p-4 bg-white border border-slate-200/90 rounded-xl shadow-2xs">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Power Shifted</span>
          <div className="mt-1 flex items-baseline gap-2">
            <span className="text-2xl font-bold font-mono text-blue-700">
              {totalShifted.toFixed(2)}
            </span>
            <span className="text-xs text-slate-500">Megawatts (MW)</span>
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            Across {recommendations.length} direct corridor recommendation(s)
          </div>
        </div>

        <div className="p-4 bg-white border border-slate-200/90 rounded-xl shadow-2xs">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Post-Transfer Balance</span>
          <div className="mt-1 flex items-baseline gap-2">
            <span className="text-2xl font-bold font-mono text-emerald-600 flex items-center gap-1.5">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span>{simulationResult.allOverloadsResolved ? '100% Resolved' : 'Partially Resolved'}</span>
            </span>
          </div>
          <div className="text-[11px] text-slate-500 mt-1">
            All projected zone loads constrained below rated capacity
          </div>
        </div>
      </div>

      {/* Transfer Recommendation Schedule Table */}
      <div className="bg-white border border-slate-200/90 rounded-xl overflow-hidden shadow-2xs">
        <div className="px-5 py-3.5 border-b border-slate-100 flex items-center justify-between">
          <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <ArrowRightLeft className="w-4 h-4 text-blue-600" />
            <span>Recommended Transfer Directives</span>
          </h3>
          <span className="text-xs text-slate-400 font-mono">Algorithm: Constrained Greedy Dispatch</span>
        </div>

        {recommendations.length === 0 ? (
          <div className="p-12 text-center text-slate-500 space-y-2">
            <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
            <h4 className="text-sm font-bold text-slate-900">Zero Transfers Required</h4>
            <p className="text-xs text-slate-500 max-w-md mx-auto">
              All microgrid zones are currently projected to operate below 100% capacity. No redistribution of load is necessary.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="bg-slate-50/80 border-b border-slate-200/90 text-slate-500 font-semibold uppercase text-[11px]">
                  <th className="py-3 px-4">#</th>
                  <th className="py-3 px-4">Transfer Route</th>
                  <th className="py-3 px-4">Shift Amount</th>
                  <th className="py-3 px-4">Source Pre/Post</th>
                  <th className="py-3 px-4">Destination Pre/Post</th>
                  <th className="py-3 px-4">Corridor Type</th>
                  <th className="py-3 px-4 min-w-[240px]">Reason &amp; Rationale</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-mono tabular-nums">
                {recommendations.map((rec, i) => (
                  <tr key={i} className="hover:bg-slate-50/70 transition-colors">
                    <td className="py-3.5 px-4 font-sans font-bold text-slate-400">{i + 1}</td>
                    <td className="py-3.5 px-4 font-sans font-semibold text-slate-900">
                      <div className="flex items-center gap-2">
                        <span className="text-rose-600 font-bold">{rec.sourceZoneName}</span>
                        <ArrowRight className="w-3.5 h-3.5 text-blue-600 shrink-0" />
                        <span className="text-emerald-700 font-bold">{rec.targetZoneName}</span>
                      </div>
                    </td>
                    <td className="py-3.5 px-4 font-bold text-blue-700 text-sm">
                      +{rec.transferMw.toFixed(2)} MW
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">
                      <div>Pre: {rec.sourcePreLoadMw.toFixed(1)} MW</div>
                      <div className="text-emerald-700 font-semibold">Post: {rec.sourcePostLoadMw.toFixed(1)} / {rec.sourceCapacityMw} MW</div>
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">
                      <div>Pre: {rec.targetPreLoadMw.toFixed(1)} MW</div>
                      <div className="text-slate-900 font-semibold">Post: {rec.targetPostLoadMw.toFixed(1)} / {rec.targetCapacityMw} MW</div>
                    </td>
                    <td className="py-3.5 px-4 font-sans">
                      <span
                        className={`text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full ${
                          rec.transferType === 'INTRA_PARTITION'
                            ? 'bg-blue-50 text-blue-700 border border-blue-200'
                            : 'bg-purple-50 text-purple-700 border border-purple-200'
                        }`}
                      >
                        {rec.transferType === 'INTRA_PARTITION' ? 'Intra-Sector Line' : 'Cross-Tie Line'}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 font-sans text-slate-600 text-xs leading-relaxed max-w-sm">
                      {rec.reason}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Before / After Load Comparison Matrix */}
      <div className="bg-white border border-slate-200/90 rounded-xl p-5 shadow-2xs space-y-4">
        <h3 className="text-sm font-bold text-slate-900 flex items-center justify-between">
          <span>Projected Load Before &amp; After Transfer Balancing</span>
          <span className="text-xs font-normal text-slate-400 font-mono">Target Threshold: &le; 100%</span>
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {zones.map((zone) => {
            const preLoad = zone.forecastLoadMw;
            const postLoad = zone.postLoadMw ?? preLoad;
            const preUtil = (preLoad / zone.capacityMw) * 100;
            const postUtil = (postLoad / zone.capacityMw) * 100;
            const wasOverloaded = preLoad > zone.capacityMw;
            const isRelieved = wasOverloaded && postLoad <= zone.capacityMw;

            return (
              <div
                key={zone.id}
                className={`p-4 rounded-xl border transition-all ${
                  wasOverloaded
                    ? 'border-blue-200 bg-blue-50/20'
                    : 'border-slate-200/80 bg-slate-50/40'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-slate-900 text-sm">{zone.name}</span>
                  <span className="text-xs text-slate-500 font-mono">Cap: {zone.capacityMw} MW</span>
                </div>

                <div className="mt-3 space-y-2 text-xs font-mono tabular-nums">
                  <div className="flex justify-between items-center text-slate-500">
                    <span>Forecast (Before):</span>
                    <span className={wasOverloaded ? 'text-rose-600 font-bold' : 'text-slate-700'}>
                      {preLoad.toFixed(1)} MW ({preUtil.toFixed(1)}%)
                    </span>
                  </div>

                  <div className="flex justify-between items-center font-bold text-slate-900">
                    <span>Adjusted (After):</span>
                    <span className={isRelieved ? 'text-emerald-700' : 'text-blue-700'}>
                      {postLoad.toFixed(1)} MW ({postUtil.toFixed(1)}%)
                    </span>
                  </div>

                  {/* Progress bar comparison */}
                  <div className="w-full bg-slate-200 rounded-full h-2 overflow-hidden mt-1">
                    <div
                      className={`h-full rounded-full transition-all ${
                        postUtil > 100 ? 'bg-rose-600' : 'bg-emerald-600'
                      }`}
                      style={{ width: `${Math.min(100, postUtil)}%` }}
                    />
                  </div>
                </div>

                {isRelieved && (
                  <div className="mt-2 text-[11px] text-emerald-700 font-sans font-medium flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Relieved {(preLoad - postLoad).toFixed(2)} MW safely</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Graph Visualizer With Flow Paths */}
      <div className="space-y-3">
        <h3 className="text-sm font-bold text-slate-900">
          Transfer Flow Topology Map
        </h3>
        <GridTopologyGraph
          zones={zones}
          connections={connections}
          recommendations={recommendations}
          partitions={partitions}
          onSelectZone={onSelectZone}
        />
      </div>

      {/* Safety Invariant Rules Banner */}
      <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-600 space-y-2">
        <div className="flex items-center gap-2 font-bold text-slate-900">
          <ShieldCheck className="w-4 h-4 text-emerald-600" />
          <span>Core Engineering Invariants Enforced by Java LoadBalancer</span>
        </div>
        <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 text-slate-600 list-disc list-inside">
          <li><strong>Graph Adjacency:</strong> Transfers only occur across direct topological edges.</li>
          <li><strong>Thermal Line Limits:</strong> Individual transfers never exceed link ratings (25–35 MW).</li>
          <li><strong>Recipient Headroom:</strong> Recipient zones are never pushed beyond safety margin (92% threshold).</li>
          <li><strong>Educational Simulation:</strong> Recommendations are advisory and do not switch physical equipment.</li>
        </ul>
      </div>
    </div>
  );
};
