import React from 'react';
import { Menu, Play, RefreshCw, AlertTriangle, CheckCircle2, ChevronDown } from 'lucide-react';
import { NavTab } from './Sidebar';

interface HeaderProps {
  currentTab: NavTab;
  onOpenMobileMenu: () => void;
  onRunSimulation: () => void;
  isRunningSimulation: boolean;
  hasOverloads: boolean;
  overloadCount: number;
  selectedScenario: string;
  onSelectScenario: (scenario: string) => void;
}

export const Header: React.FC<HeaderProps> = ({
  currentTab,
  onOpenMobileMenu,
  onRunSimulation,
  isRunningSimulation,
  hasOverloads,
  overloadCount,
  selectedScenario,
  onSelectScenario,
}) => {
  const getTabTitle = (tab: NavTab) => {
    switch (tab) {
      case 'overview':
        return {
          title: 'Grid overview',
          desc: 'Monitor zone demand, forecast upcoming load, and review safe transfer recommendations.',
        };
      case 'grid-map':
        return {
          title: 'Microgrid Topology Map',
          desc: 'Interactive graph visualization of interconnected zones, transmission limits, and partition cuts.',
        };
      case 'zones':
        return {
          title: 'Zone Capacity & Telemetry',
          desc: 'Searchable inventory of regional load parameters, capacities, utilization percentages, and status.',
        };
      case 'forecasts':
        return {
          title: 'Load Forecasting Analytics',
          desc: 'Ordinary Least Squares linear trend projection generated by Python from historical readings.',
        };
      case 'transfer-plan':
        return {
          title: 'Recommended Transfer Plan',
          desc: 'Constrained load balancing suggestions computed in Java adhering to graph edge limits.',
        };
      case 'guide':
        return {
          title: 'Project Guide & Presentation',
          desc: 'ADSA divide-and-conquer analysis, Java OOP architecture, Python math derivation, and demo script.',
        };
    }
  };

  const { title, desc } = getTabTitle(currentTab);

  return (
    <header className="sticky top-0 z-30 bg-white/95 backdrop-blur-xs border-b border-slate-200/80 px-4 sm:px-6 lg:px-8 py-3.5 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
      <div className="flex items-center gap-3">
        <button
          onClick={onOpenMobileMenu}
          className="lg:hidden p-2 text-slate-500 hover:text-slate-700 hover:bg-slate-100 rounded-lg"
          aria-label="Open navigation menu"
        >
          <Menu className="w-5 h-5" />
        </button>

        <div>
          <h1 className="text-xl font-bold tracking-tight text-slate-900">{title}</h1>
          <p className="text-xs text-slate-500 hidden sm:block mt-0.5">{desc}</p>
        </div>
      </div>

      <div className="flex items-center flex-wrap gap-2.5">
        {/* Scenario preset selector */}
        <div className="relative inline-block">
          <select
            value={selectedScenario}
            onChange={(e) => onSelectScenario(e.target.value)}
            disabled={isRunningSimulation}
            className="appearance-none bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-700 text-xs font-medium rounded-lg pl-3 pr-8 py-2 focus:outline-hidden focus:ring-2 focus:ring-blue-500/20 cursor-pointer disabled:opacity-50"
          >
            <option value="default">Standard Peak Surge (North)</option>
            <option value="heatwave">Heatwave Alert (North + South)</option>
            <option value="balanced">Nominal Balanced Grid (All Safe)</option>
          </select>
          <ChevronDown className="w-3.5 h-3.5 text-slate-400 absolute right-2.5 top-1/2 -translate-y-1/2 pointer-events-none" />
        </div>

        {/* Live Grid health pill */}
        <div className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-50 border border-slate-200/70 text-xs font-medium">
          {hasOverloads ? (
            <>
              <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" />
              <span className="text-rose-700">{overloadCount} Zone{overloadCount > 1 ? 's' : ''} at Risk</span>
            </>
          ) : (
            <>
              <span className="w-2 h-2 rounded-full bg-emerald-500" />
              <span className="text-emerald-700">Grid Nominal</span>
            </>
          )}
        </div>

        {/* Primary Action: Run Simulation */}
        <button
          onClick={onRunSimulation}
          disabled={isRunningSimulation}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 active:bg-blue-800 text-white rounded-lg text-xs font-semibold shadow-xs transition-colors disabled:opacity-60 cursor-pointer"
        >
          {isRunningSimulation ? (
            <>
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              <span>Simulating...</span>
            </>
          ) : (
            <>
              <Play className="w-3.5 h-3.5 fill-white" />
              <span>Run Simulation</span>
            </>
          )}
        </button>
      </div>
    </header>
  );
};
